In [2]:
import pandas as pd

df = pd.read_csv("categorical_encoding_dataset.csv")

In [3]:
df.head(10)

,Customer_ID,City,Gender,Payment_Method,Education_Level,Satisfaction_Level,Subscribed,Product_Category,Purchased
0,1001,Chennai,Female,Credit Card,Master,High,No,Furniture,No
1,1002,Kolkata,Male,Cash,PhD,Medium,No,Fashion,No
2,1003,Bangalore,Male,UPI,High School,Low,No,Furniture,Yes
3,1004,Kolkata,Female,Cash,High School,Medium,Yes,Jewelry,No
4,1005,Kolkata,Female,Cash,Bachelor,Low,Yes,Jewelry,Yes
5,1006,Mumbai,Female,Credit Card,Master,High,No,Books,No
6,1007,Bangalore,Male,UPI,Master,Low,No,Jewelry,Yes
7,1008,Bangalore,Female,Debit Card,Bachelor,Low,Yes,Electronics,Yes
8,1009,Bangalore,Male,Debit Card,Bachelor,Low,No,Beauty,Yes
9,1010,Kolkata,Male,Credit Card,Master,High,No,Toys,Yes

1. Label Encoding
2. One - Hot Encoding
3. Ordinal Encoding
4. Binary Encoding

<h1>Label Encoding</h1>

Assigns each category with a unique integer.

In [ ]:
pip install scikit-learn

In [4]:
from sklearn.preprocessing import LabelEncoder

df['City']

le = LabelEncoder()
encoded = le.fit_transform(df['City'])

In [5]:
encoded

array([1, 3, 0, 3, 3, 4, 0, 0, 0, 3, 1, 0, 3, 4, 1, 4, 1, 3, 2, 1, 4, 3,
       1, 2, 2, 0, 0, 4, 1, 1, 0, 1, 1, 2, 0, 3, 0, 3, 2, 4, 1, 2, 1, 4,
       4, 2, 4, 3, 4, 1, 1, 1, 1, 3, 0, 2, 1, 4, 1, 4, 4, 1, 3, 4, 4, 1,
       4, 4, 1, 1, 2, 3, 3, 4, 3, 4, 2, 1, 1, 1, 3, 2, 3, 3, 2, 2, 2, 2,
       1, 0, 0, 2, 0, 0, 2, 0, 3, 4, 4, 2])

<h1>One-Hot Encoding</h1>

Creates binary columns for each category

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df[['Payment_Method']])
encoded

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]])

<h1>Ordinal Encoding</h1>

Used when categories have a meaningful order

In [10]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[["Low","Medium","High"]])

encoded = oe.fit_transform(df[['Satisfaction_Level']])
encoded

array([[2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.]])

<h1>Binary Encoding</h1>

In [12]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (2.4.4)
Requirement already satisfied: pandas>=1.0.5 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (3.0.2)
Collecting patsy>=0.5.1 (from category_encoders)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.17.1)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.6-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 3.7 MB/s  0:00:02eta 0:00:01m
Installing collected packages: patsy, statsmodels, category_encoders
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [category_encoders]statsmodels]
Successfully installed category_encoders-2.9.0 patsy-1.0.2 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

In [13]:
import category_encoders as ce


encoder = ce.BinaryEncoder(cols="Product_Category")

encoded = encoder.fit_transform(df)
encoded

,Customer_ID,City,Gender,Payment_Method,Education_Level,Satisfaction_Level,Subscribed,Product_Category_0,Product_Category_1,Product_Category_2,Product_Category_3,Purchased
0,1001,Chennai,Female,Credit Card,Master,High,No,0,0,0,1,No
1,1002,Kolkata,Male,Cash,PhD,Medium,No,0,0,1,0,No
2,1003,Bangalore,Male,UPI,High School,Low,No,0,0,0,1,Yes
3,1004,Kolkata,Female,Cash,High School,Medium,Yes,0,0,1,1,No
4,1005,Kolkata,Female,Cash,Bachelor,Low,Yes,0,0,1,1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Bangalore,Male,Debit Card,High School,Medium,Yes,0,1,1,1,Yes
96,1097,Kolkata,Male,Credit Card,Master,High,No,1,0,0,0,No
97,1098,Mumbai,Male,UPI,Bachelor,Low,No,1,0,0,1,Yes
98,1099,Mumbai,Female,Debit Card,PhD,Low,No,1,0,0,0,Yes
99,1100,Delhi,Female,Cash,Master,Low,Yes,0,1,1,1,Yes

In [14]:
df

,Customer_ID,City,Gender,Payment_Method,Education_Level,Satisfaction_Level,Subscribed,Product_Category,Purchased
0,1001,Chennai,Female,Credit Card,Master,High,No,Furniture,No
1,1002,Kolkata,Male,Cash,PhD,Medium,No,Fashion,No
2,1003,Bangalore,Male,UPI,High School,Low,No,Furniture,Yes
3,1004,Kolkata,Female,Cash,High School,Medium,Yes,Jewelry,No
4,1005,Kolkata,Female,Cash,Bachelor,Low,Yes,Jewelry,Yes
...,...,...,...,...,...,...,...,...,...
95,1096,Bangalore,Male,Debit Card,High School,Medium,Yes,Toys,Yes
96,1097,Kolkata,Male,Credit Card,Master,High,No,Groceries,No
97,1098,Mumbai,Male,UPI,Bachelor,Low,No,Automobile,Yes
98,1099,Mumbai,Female,Debit Card,PhD,Low,No,Groceries,Yes
99,1100,Delhi,Female,Cash,Master,Low,Yes,Toys,Yes

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

education_order=['High School','Bachelor','Master','PhD']
satisfaction_order= ['Low','Medium','High']

le = LabelEncoder()
oe = OrdinalEncoder(categories=[education_order,satisfaction_order])

df['Subscribed'] = le.fit_transform(df['Subscribed'])
df['Purchased'] = le.fit_transform(df['Purchased'])
df[['Education_Level','Satisfaction_Level']] = oe.fit_transform(df[['Education_Level','Satisfaction_Level']])

In [18]:
df = pd.get_dummies(df,columns=['City','Gender','Payment_Method','Product_Category'])

In [19]:
df

,Customer_ID,Education_Level,Satisfaction_Level,Subscribed,Purchased,City_Bangalore,City_Chennai,City_Delhi,City_Kolkata,City_Mumbai,...,Product_Category_Automobile,Product_Category_Beauty,Product_Category_Books,Product_Category_Electronics,Product_Category_Fashion,Product_Category_Furniture,Product_Category_Groceries,Product_Category_Jewelry,Product_Category_Sports,Product_Category_Toys
0,1001,2.0,2.0,0,0,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,1002,3.0,1.0,0,0,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,1003,0.0,0.0,0,1,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,1004,0.0,1.0,1,0,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
4,1005,1.0,0.0,1,1,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,0.0,1.0,1,1,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
96,1097,2.0,2.0,0,0,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
97,1098,1.0,0.0,0,1,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,False
98,1099,3.0,0.0,0,1,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
99,1100,2.0,0.0,1,1,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True

In [20]:
df.to_csv("encoded_data.csv", index=False)