# PCA (Principal Component Analysis)

<strong style="color:red;">PCA is for unsupervised</strong>

Principal Component analysis is one of the most important dimensionality reduction techniques in Machine Learning.

It helps us:

- Reduce the number of features
- Remove the redundancy
- Visualize high-dimension data
- speed up model training
- Reduce overfitting

## Why Do We need PCA?

Cols : Student, Height, Weight, ShoeSize

Notice: 

- Taller students generally have larger shoe sizes.
- Height and shoe size are highly correlated.

Therefore both features are carrying almost the same information.

PCA helps us to combine such features into a smaller set of meaningful features while preserving maximum information.

### Terminology

##### Variance : 
Variance tells how spread out data is.

Dataset A = [10,10,10,10,10]
variance = 0 

Dataset B = [5,10,15,30,45]
Variance = High

More variance means more information

PCA tries to preserve directions with maximum Variance

##### Covariance :
Covariance tells how two variables move together.

Positive Covariance

Height(high)
Weight (high)


Negative Covariance

Temperature(high)
Sweater sales (low)


PCA uses covariance to find relationships between features.


##### Eigenvectors and Eigenvalues


Eignevectors:

    Direction of maximum variance.

Eigenvalue:

    Amount of variance captured in that direction

### How we solve it

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
X = load_wine().data
y = load_wine().target

In [7]:
import pandas as pd

df = pd.DataFrame(X)

In [8]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [4]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [9]:
df = pd.DataFrame(X_scaled)

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.518613,-0.562250,0.232053,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009
1,0.246290,-0.499413,-0.827996,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242
2,0.196879,0.021231,1.109334,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148
3,1.691550,-0.346811,0.487926,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574
4,0.295700,0.227694,1.840403,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874

In [19]:
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

In [20]:
pca.explained_variance_ratio_

array([0.36198848, 0.1920749 ])