## Decision Tree

In [1]:
data = {
    'Outlook':['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain'],
    'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
    'Humidity':['High','High','High','High','Normal','Normal','Normal',"High",'Normal','Normal','Normal','High','Normal','High'],
    'Play':[0,0,1,1,1,0,1,0,1,1,1,1,1,0]
}

In [2]:
import pandas as pd
df = pd.DataFrame(data)

In [3]:
df

     Outlook Temperature Humidity  Play
0      Sunny         Hot     High     0
1      Sunny         Hot     High     0
2   Overcast         Hot     High     1
3       Rain        Mild     High     1
4       Rain        Cool   Normal     1
5       Rain        Cool   Normal     0
6   Overcast        Cool   Normal     1
7      Sunny        Mild     High     0
8      Sunny        Cool   Normal     1
9       Rain        Mild   Normal     1
10     Sunny        Mild   Normal     1
11  Overcast        Mild     High     1
12  Overcast         Hot   Normal     1
13      Rain        Mild     High     0

<h3>To Check the Purity , We use:</h3>

- Entropy
- Gini Index

<h3>What feature is needed to select for splitting</h3>

 - Information Gain

- Entropy ranges: 0 - 1
- Gini ranges: 0 - 0.5

In [4]:
from sklearn.datasets import load_iris

data = load_iris().data

df = pd.DataFrame(data,columns=load_iris().feature_names)

In [5]:
df.head(20)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
15                5.7               4.4                1.5               0.4
16                5.4               3.9                1.3               0.4
17                5.1               3.5                1.4               0.3
18                5.7               3.8                1.7               0.3
19                5.1               3.8                1.5               0.3

Whenever your dataset is small => Entropy<br>
Whenever your dataset is large => Gini Index